# Generated by Django 3.2.6 on 2021-08-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rating_ratingstar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Rating star', 'verbose_name_plural': 'Rating stars'},
        ),
    ]
