# Generated by Django 3.2.6 on 2021-08-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_rating_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.job', verbose_name='Job'),
        ),
    ]
